### ISSUE TITLE
Passive Perception is not working for hidden Neutral/Friendly tokens

### ISSUE THREAD

**Issue by Pawper** [herasrobert/icu5e#3]
Hello,

Passive perception only reveals a hidden token if it is set to Hostile, otherwise it remains hidden. Is this a feature or a bug? I would like to use it for Neutral/Friendly as well.

**Comment by herasrobert** [comment]
Hi and thanks for using the module. It was never meant to reveal non-hostile tokens. However, if enough people would like it that way, I'm open to trying write parts of the code so it works that way.

**Comment by Pawper** [comment]
I'm able to work around it, but it did throw me, as I have stuff like a friendly mimic that sneaks its way into the players' inventory, and I'm using Loot Sheet 5e to make containers such as secret treasure chests. I just have to mark these things as hostile now, which I think will be fine.
