### ISSUE TITLE
Suggestion Feature: Half-Viewable Enemies

### ISSUE THREAD

**Issue by NukeMaster0** [herasrobert/icu5e#4]
What I mean by this is could there be a feature where it allows only a **_few_** players to be able to see one token while the others can't see it?

Ex: Player 1 sees a ghost, but players 2-4 can't see the ghost. You have a "Stealth Mode" and it might be a cool feature if you would consider it someday. Say some players are trapped in a room and are forced to face all those they have killed but only some can see it while others don't.

Thank you!

**Comment by herasrobert** [comment]
It's something I'm hoping to look into in future releases. Right now the Stealth Mode is tricky and I consider it somewhat hacky. Once I cement that, I plan to look into having it work for enemies as I think it would be really cool if only enemies you could see were revealed to you.
